name: windows signtool exe
description: support for windows signtool.exe wiht/without password required
branding:
  icon: 'award'
  color: 'green'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  password:
    description: the password for cert if needed
    required: false
  sign_desc:
    description: sign description "/d xxx"
    required: false
  folder:
    description: 'The folder that contains the files to sign.'
    required: true
  recursive:
    description: 'Recursively search for supported files.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
